#!/usr/bin/env python3
"""Regenerate README.md from index.json."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
INDEX_PATH = ROOT / "index.json"
README_PATH = ROOT / "README.md"
FORGE_REPO = "https://github.com/ficiverson/skills-forge"


def _render_skill_table(skills: list[dict], base_url: str) -> str:
    header = "\n".join(
        [
            "| Category | Skill | Latest | Version | SHA256 | Download |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    rows: list[str] = []

    for skill in sorted(skills, key=lambda s: (s.get("category", ""), s.get("name", ""))):
        category = skill.get("category", "")
        name = skill.get("name", "")
        latest = skill.get("latest", "")
        versions = skill.get("versions", [])

        for version in versions:
            ver = version.get("version", "")
            sha256 = version.get("sha256", "")
            pack_path = version.get("path", "")
            download_url = f"{base_url.rstrip('/')}/{pack_path}" if pack_path else ""
            rows.append(
                f"| `{category}` | `{name}` | `{latest}` | `{ver}` | `{sha256}` | [download]({download_url}) |"
            )

    if not rows:
        rows.append("| - | - | - | - | - | - |")

    return "\n".join([header, *rows])


def main() -> int:
    index = json.loads(INDEX_PATH.read_text(encoding="utf-8"))
    skills = index.get("skills", [])
    base_url = index.get("base_url", "")
    registry_name = index.get("registry_name", "skill-registry")
    updated_at = index.get("updated_at", "")

    content = "\n".join(
        [
            f"# {registry_name}",
            "",
            "This registry was created and is maintained with [skills-forge]"
            f"({FORGE_REPO}).",
            "",
            "## Registry index",
            "",
            f"- `format_version`: `{index.get('format_version', '')}`",
            f"- `base_url`: `{base_url}`",
            f"- `updated_at`: `{updated_at}`",
            "",
            "## Skills",
            "",
            _render_skill_table(skills, base_url),
            "",
            "## Maintainer workflow",
            "",
            "- Regenerate docs manually with `python3 regenerate-readme.py`.",
            "- Wire a local git pre-push hook to enforce it:",
            "",
            "```bash",
            "mkdir -p .git/hooks",
            "cp .githooks/pre-push .git/hooks/pre-push",
            "chmod +x .git/hooks/pre-push",
            "```",
            "",
            "<!-- Generated by regenerate-readme.py -->",
            "",
        ]
    )

    README_PATH.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
